services:
  db:
    image: postgres:latest
    container_name: postgresql_db
    ports:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: volume
        source: db-volume
        target: "/var/lib/pgsql/data"
        read_only: false

  memcachedb:
    image: memcached:latest
    container_name: memcached_db
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - ${MEMCACHED_PORT}

volumes:
  db-volume:
    name: postgresql_volume


